#:schema node_modules/wrangler/config-schema.json
name = "gemini-proxy-worker"
main = "src/index.ts"
compatibility_date = "2024-08-06"
compatibility_flags = ["nodejs_compat"]

[placement]
mode = "smart"

[vars]
NODE_TLS_REJECT_UNAUTHORIZED = 0
